### ISSUE TITLE
自动换行时出现标点符号处在第一位的情况

### ISSUE THREAD

**Issue by YanxuLi** [lybeat/PlumbTextView#3]
在文字较长，一列显示不下，自动换行时，如果正好是标点符号，那么第二列的第一位就变成了标点，体验比较不好，请问作者有什么办法解决吗？急~~~

**Comment by lybeat** [comment]
标点符号是需要保留的吗？不需要保留标点符号的话，可以将标点符号添加到正则里面。要保留的话只能自己处理。

**Comment by YanxuLi** [comment]
已自行处理
